version: '3.1'

services:
  db:
    image: postgres:16.1
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: toor
  # server:
  #   build: .
  #   ports:
  #     - "3000:3000"
  #   env_file: ./crates/server/.env
  #   depends_on:
  #     - db
  #   volumes:
  #     - ./webapp:/opt/webapp
